# Generated by Django 4.1.5 on 2023-02-05 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverName', models.CharField(default='', max_length=150)),
                ('carType', models.CharField(default='sedan', max_length=20)),
                ('maxCapacity', models.IntegerField(default=4)),
                ('licensePlateNumber', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RideCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverName', models.CharField(default='', max_length=150)),
                ('carType', models.CharField(default='sedan', max_length=20)),
                ('maxCapacity', models.IntegerField(default=4)),
                ('licensePlateNumber', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RideSharer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharerridepk', models.IntegerField(default=0)),
                ('sharerName', models.CharField(default='', max_length=150)),
                ('numPassengers', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.CharField(default='', max_length=150, primary_key=True, serialize=False)),
                ('isDriver', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('arrivalTime', models.DateTimeField()),
                ('isSharing', models.CharField(choices=[('shareable', 'shareable'), ('private', 'private')], max_length=20)),
                ('ownerName', models.CharField(default='', max_length=150)),
                ('driverName', models.CharField(default='', max_length=150)),
                ('specialRequest', models.CharField(default='', max_length=300)),
                ('cartypeRequest', models.CharField(default='sedan', max_length=20)),
                ('rideStatus', models.CharField(default='open', max_length=20)),
                ('ridecar', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ridecar', to='userAdmin.ridecar')),
                ('ridesharer', models.ManyToManyField(blank=True, related_name='ridesharer', to='userAdmin.ridesharer')),
            ],
        ),
    ]
