# Generated by Django 4.1.5 on 2023-02-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ridesharercount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ridecar',
            name='driverspecialRequest',
            field=models.CharField(default='', max_length=300),
        ),
    ]
