# Generated by Django 4.1.5 on 2023-02-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0002_ride_ridesharercount_ridecar_driverspecialrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridecar',
            name='driverspecialRequest',
        ),
        migrations.AddField(
            model_name='car',
            name='driverspecialRequest',
            field=models.CharField(default='', max_length=300),
        ),
    ]
