# Generated by Django 4.1.5 on 2023-02-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0003_remove_ridecar_driverspecialrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridecar',
            name='driverspecialRequest',
            field=models.CharField(default='', max_length=300),
        ),
    ]
